version: '3.7'
services:
  db:
    image: postgres:11.7
    container_name: db
    ports:
      - '4005:5432'
    volumes:
      - ./_dbscript:/docker-entrypoint-initdb.d:delegated
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - local

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - local

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin 
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    networks:
      - local
    
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - '4222:4222'
    networks:
      - local

  accounting:
    build: ./packages/accounting
    container_name: accounting
    ports:
      - '3003:3000'
    networks:
      - local
    volumes:
      - ./packages/accounting:/usr/src/app:delegated
      - ./node_modules:/usr/src/app/node_modules:delegated
    depends_on:
      - db
    command: 'npm start'
    env_file:
      - ./.env

  billing:
    build: ./packages/billing
    container_name: billing
    ports:
      - '3001:3000'
    networks:
      - local
    volumes:
      - ./packages/billing:/usr/src/app:delegated
      - ./node_modules:/usr/src/app/node_modules:delegated
    command: 'npm start'
    env_file:
      - ./.env

  ordering:
    build: ./packages/ordering
    container_name: ordering
    ports:
      - '3002:3000'
    networks:
      - local
    volumes:
      - ./packages/ordering:/usr/src/app:delegated
      - ./node_modules:/usr/src/app/node_modules:delegated
    depends_on:
      - db
    command: 'npm start'
    env_file:
      - ./.env

  products:
    build: ./packages/products
    container_name: products
    ports:
      - '3004:3000'
    networks:
      - local
    volumes:
      - ./packages/products:/usr/src/app:delegated
      - ./node_modules:/usr/src/app/node_modules:delegated
    depends_on:
      - db
    command: 'npm start'
    env_file:
      - ./.env

  graphql:
    build: ./packages/graphql
    container_name: graphql
    ports:
      - '3000:3000'
    networks:
      - local
    volumes:
      - ./packages/graphql:/usr/src/app:delegated
      - ./node_modules:/usr/src/app/node_modules:delegated
    depends_on:
      - accounting
      - billing
      - ordering
    command: 'npm start'
    env_file:
      - ./.env

networks:
  local:
    driver: bridge
